# Generated by Django 4.0.4 on 2024-03-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
